/* Generated By:JavaCC: Do not edit this line. AtroemTokenManager.java */
import java.util.*;

/** Token Manager. */
public class AtroemTokenManager implements AtroemConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x100000L) != 0L)
            return 17;
         if ((active0 & 0xf80000000cL) != 0L)
            return 1;
         return -1;
      case 1:
         if ((active0 & 0xcL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 4;
               jjmatchedPos = 1;
            }
            return 18;
         }
         return -1;
      case 2:
         if ((active0 & 0x8L) != 0L)
            return 18;
         if ((active0 & 0x4L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 2;
            return 18;
         }
         return -1;
      case 3:
         if ((active0 & 0x4L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 3;
            return 18;
         }
         return -1;
      case 4:
         if ((active0 & 0x4L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 4;
            return 18;
         }
         return -1;
      case 5:
         if ((active0 & 0x4L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 5;
            return 18;
         }
         return -1;
      case 6:
         if ((active0 & 0x4L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 6;
            return 18;
         }
         return -1;
      case 7:
         if ((active0 & 0x4L) != 0L)
            return 18;
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 22;
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 34:
         return jjStartNfaWithStates_0(0, 20, 17);
      case 37:
         return jjStopAtPos(0, 27);
      case 38:
         return jjStopAtPos(0, 7);
      case 40:
         return jjStopAtPos(0, 29);
      case 41:
         return jjStopAtPos(0, 30);
      case 42:
         return jjStopAtPos(0, 25);
      case 43:
         jjmatchedKind = 23;
         return jjMoveStringLiteralDfa1_0(0x40000L);
      case 44:
         return jjStopAtPos(0, 21);
      case 45:
         jjmatchedKind = 24;
         return jjMoveStringLiteralDfa1_0(0x80000L);
      case 47:
         return jjStopAtPos(0, 26);
      case 58:
         return jjStopAtPos(0, 13);
      case 59:
         return jjStopAtPos(0, 17);
      case 60:
         jjmatchedKind = 9;
         return jjMoveStringLiteralDfa1_0(0x8000L);
      case 61:
         jjmatchedKind = 14;
         return jjMoveStringLiteralDfa1_0(0x800L);
      case 62:
         jjmatchedKind = 10;
         return jjMoveStringLiteralDfa1_0(0x10000L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x8000000000L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x4000000000L);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x1000000000L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x800000000L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x8L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x4L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x2000000000L);
      case 91:
         return jjStopAtPos(0, 33);
      case 93:
         return jjStopAtPos(0, 34);
      case 94:
         return jjStopAtPos(0, 28);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x300000000000L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x8000000000000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x40L);
      case 104:
         return jjMoveStringLiteralDfa1_0(0x2800000000000L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x4000000000000L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x1000000000000L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x40000000000L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x80000000000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x400000000002L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x30000000000L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x20L);
      case 123:
         return jjStopAtPos(0, 31);
      case 124:
         return jjStopAtPos(0, 8);
      case 125:
         return jjStopAtPos(0, 32);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 43:
         if ((active0 & 0x40000L) != 0L)
            return jjStopAtPos(1, 18);
         break;
      case 45:
         if ((active0 & 0x80000L) != 0L)
            return jjStopAtPos(1, 19);
         break;
      case 61:
         if ((active0 & 0x800L) != 0L)
            return jjStopAtPos(1, 11);
         else if ((active0 & 0x1000L) != 0L)
            return jjStopAtPos(1, 12);
         else if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(1, 15);
         else if ((active0 & 0x10000L) != 0L)
            return jjStopAtPos(1, 16);
         break;
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000L);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000L);
      case 73:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x2900000000040L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000020L);
      case 105:
         if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x1020000000008L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x640000000000L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000000L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x6L);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 67:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStopAtPos(2, 36);
         break;
      case 68:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStopAtPos(2, 38);
         break;
      case 77:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStopAtPos(2, 37);
         break;
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000L);
      case 84:
         if ((active0 & 0x800000000L) != 0L)
            return jjStopAtPos(2, 35);
         break;
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0xa080000000000L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x5000000000000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x2L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x40L);
      case 110:
         if ((active0 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(2, 3, 18);
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x4L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x600000000020L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x940000000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000000L);
      case 76:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStopAtPos(3, 39);
         break;
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x20L);
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000000L);
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x4L);
      case 105:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStopAtPos(3, 42);
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000000L);
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000002L);
      case 111:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStopAtPos(3, 41);
         else if ((active0 & 0x100000000000L) != 0L)
            return jjStopAtPos(3, 44);
         break;
      case 114:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStopAtPos(3, 50);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000000L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x40L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0xa00000000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStopAtPos(4, 47);
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000020L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x2L);
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000000L);
      case 111:
         if ((active0 & 0x40L) != 0L)
            return jjStopAtPos(4, 6);
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000000L);
      case 114:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStopAtPos(4, 49);
         return jjMoveStringLiteralDfa5_0(active0, 0x4L);
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x4L);
      case 98:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000000L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x20L);
      case 102:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000000L);
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x2L);
      case 110:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStopAtPos(5, 43);
         break;
      case 114:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStopAtPos(5, 45);
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000000L);
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000020L);
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000000L);
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x4L);
      case 112:
         return jjMoveStringLiteralDfa7_0(active0, 0x2L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 97:
         if ((active0 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(7, 2, 18);
         return jjMoveStringLiteralDfa8_0(active0, 0x2L);
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x400000000000L);
      case 114:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStopAtPos(7, 51);
         return jjMoveStringLiteralDfa8_0(active0, 0x20L);
      case 115:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStopAtPos(7, 48);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 108:
         return jjMoveStringLiteralDfa9_0(active0, 0x2L);
      case 111:
         if ((active0 & 0x20L) != 0L)
            return jjStopAtPos(8, 5);
         break;
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0x400000000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 40:
         return jjMoveStringLiteralDfa10_0(active0, 0x2L);
      case 111:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStopAtPos(9, 46);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 41:
         if ((active0 & 0x2L) != 0L)
            return jjStopAtPos(10, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   //int[] nextStates; // not used
   int startsAt = 0;
   jjnewStateCnt = 17;
   int i = 1;
   jjstateSet[0] = startState;
   //int j; // not used
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 17:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddTwoStates(10, 11);
                  else if (curChar == 34)
                  {
                     if (kind > 56)
                        kind = 56;
                  }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAddStates(0, 2);
                  }
                  else if (curChar == 34)
                     jjCheckNAddTwoStates(10, 11);
                  else if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 7;
                  else if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 18:
               case 2:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAdd(2);
                  break;
               case 3:
                  if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 52)
                     kind = 52;
                  jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 6:
                  if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 8:
                  if (curChar == 39 && kind > 55)
                     kind = 55;
                  break;
               case 9:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(10, 11);
                  break;
               case 10:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddTwoStates(10, 11);
                  break;
               case 11:
                  if (curChar == 34 && kind > 56)
                     kind = 56;
                  break;
               case 12:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(0, 2);
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAdd(13);
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(14, 15);
                  break;
               case 15:
                  if (curChar == 46)
                     jjCheckNAdd(16);
                  break;
               case 16:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 54)
                     kind = 54;
                  jjCheckNAdd(16);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 17:
               case 10:
                  jjCheckNAddTwoStates(10, 11);
                  break;
               case 0:
                  if ((0x7fffffeL & l) != 0L)
                     jjCheckNAdd(1);
                  break;
               case 18:
               case 1:
                  if ((0x7fffffe00000000L & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAddTwoStates(1, 2);
                  break;
               case 4:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 52)
                     kind = 52;
                  jjAddStates(3, 4);
                  break;
               case 7:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 17:
               case 10:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(10, 11);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 17 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   13, 14, 15, 4, 5, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", "\160\162\151\156\143\151\160\141\154\50\51", 
"\120\162\157\147\162\141\155\141", "\106\151\156", null, "\166\145\162\144\141\144\145\162\157", 
"\146\141\154\163\157", "\46", "\174", "\74", "\76", "\75\75", "\41\75", "\72", "\75", "\74\75", 
"\76\75", "\73", "\53\53", "\55\55", "\42", "\54", "\41", "\53", "\55", "\52", "\57", 
"\45", "\136", "\50", "\51", "\173", "\175", "\133", "\135", "\105\116\124", 
"\104\105\103", "\123\111\115", "\103\101\104", "\102\117\117\114", "\163\151", 
"\163\151\156\157", "\156\157\163\151", "\157\160\143\151\157\156", "\143\141\163\157", 
"\143\157\162\164\141\162", "\160\157\162\104\145\146\145\143\164\157", "\150\141\163\164\141", 
"\155\151\145\156\164\162\141\163", "\150\141\143\145\162", "\154\145\145\162", 
"\145\163\143\162\151\142\151\162", null, null, null, null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0x1ffffffffffffffL, 
};
static final long[] jjtoSkip = {
   0x1e00000000000000L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[17];
static private final int[] jjstateSet = new int[34];
static protected char curChar;
/** Constructor. */
public AtroemTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public AtroemTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 17; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String tokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   tokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, tokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  //int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
